name: CI

on:
  push:
    branches: "*"

  schedule:
    - cron: "0 0 * * *"

jobs:
  Tests:
    name: Run notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Enable Pip Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install -r dev-requirements.txt
      - name: Running Tests
        run: |
          pytest -v --current-env --nbval-lax notebooks/*.ipynb
